### ISSUE TITLE
GLPI application token not provide - when using glpi_username and glpi_password

### ISSUE THREAD

**Issue by danaelg** [unistra/ansible-collection-glpi#5]
Hello,

When we want to use glpi_username and glpi_password instead of glpi_apptoken and glpi_usertoken we get the following error :
```
[WARNING]:  * Failed to parse /home/vagrant/inventory_glpi.yml with ansible_collections.unistra.glpi.plugins.inventory.inv plugin: GLPI application token not provided
```

Here is my config file : 
```yaml
---

plugin: unistra.glpi.inv

glpi_url: https://example.org/apirest.php
glpi_verify_certs: false
glpi_username: dgiordana
glpi_password: "obviouslynotmypassword"

queries:
   [...]
```
